version: '3.8'

services:
  api-gateway:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge