spring:
  #profiles:
    #active: local

  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: health
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/health

        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**, /docs/auth/v3/api-docs
          uri: http://auth-service:8084
          filters:
          #- StripPrefix=1

        - id: hotel-service
          predicates:
            - Path=/api/v1/hotels/**, /api/v1/rooms/**, /docs/hotels/v3/api-docs
          filters:
            - name: JwtAuthFilter
          uri: http://hotel-service:8081

        - id: reservation-service
          predicates:
            - Path=/api/v1/reservations/**, /docs/reservations/v3/api-docs
          filters:
            - name: JwtAuthFilter
          uri: http://reservation-service:8082

        - id: notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: JwtAuthFilter
          uri: http://notification-service:8083

        - id: payment-service
          predicates:
            - Path=/api/v1/payments/**, /docs/payments/v3/api-docs
          filters:
            - name: JwtAuthFilter
          uri: http://payment-service:8085
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: redis #localhost, redis
      port: 6379

server:
  port: 8080

springdoc:
  show-login-endpoint: false
  api-docs:
    enabled: true
    path: /docs/main/v3/api-docs
  swagger-ui:
    enabled: true
    path: /docs/main/swagger-ui.html
    config-url: /docs/main/v3/api-docs/swagger-config
    urls:
      - name: "API Gateway Service"
        url: /docs/main/v3/api-docs
      - name: "Auth Service"
        url: /docs/auth/v3/api-docs
      - name: "Hotel Service"
        url: /docs/hotels/v3/api-docs
      - name: "Reservation Service"
        url: /docs/reservations/v3/api-docs
      - name: "Payment Service"
        url: /docs/payments/v3/api-docs

jwt:
  secret: ${JWT_SECRET:ZhV3+eY767wZQ4ce+qb8PbwanES3wA8XpBvAkC2ZiVA=}
  expiration: 86400000 # 24 saat

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.hotelapp.gateway.security.JwtAuthFilter: DEBUG
