spring:
  #profiles:
    #active: local

  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: health
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/health
        - id: auth-service
          predicates:
            - Path=/api/v1/auth/**
          uri: http://auth-service:8084
          filters:
          #- StripPrefix=1

        - id: hotel-service
          predicates:
            - Path=/api/v1/hotels/**, /api/v1/rooms/**
          filters:
            - name: JwtAuthFilter
          uri: http://hotel-service:8081

        - id: reservation-service
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - name: JwtAuthFilter
          uri: http://reservation-service:8082

        - id: notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: JwtAuthFilter
          uri: http://notification-service:8083

        - id: payment-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - name: JwtAuthFilter
          uri: http://payment-service:8085
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      host: localhost #localhost, redis
      port: 6379

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:ZhV3+eY767wZQ4ce+qb8PbwanES3wA8XpBvAkC2ZiVA=}
  expiration: 86400000 # 24 saat

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.hotelapp.gateway.security.JwtAuthFilter: DEBUG
